### ISSUE TITLE
way to upgrade to angular2

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#106]
Hi all,

We should have a documented way how to upgrade to angular2, once it is out.

I thought about two nice ways:
- Have a ng-forward version which behind the scenes creates angular2 elements
- Have a script which makes most of the automatic work and warns about issues which is not covered.
  For example the script could go over and change the imports from 'ng-forward' to angular2, additionally import the core directives and warn about directives which are not imported.

What do you think about it?

A third (less cool) option would be just to document the steps :-(

Thanks,
David

**Comment by timkindberg** [comment]
I really like this idea.

I've thought about your first idea before. We should theoretically be able to call Angular 2 apis in place of the Angular 1 apis behind the scenes. However, then you are using the ng-forward layer over top of the Angular 2 layer and you probably won't want that to be the case long term. You'll probably want to actually convert to Angular 2. 

So your second idea also seems pretty good, certainly we could have a script for the basic stuff. There will most likely be plenty of things we can't do with a script though. But if we can get devs 50% there I think that would be great.

Documenting is a very realistic option and probably something we can do at a minimum.

All this being said, I'm personally not ready to start looking into this. We have a lot of work simply polyfilling Angular 2 ahead of us first.
