### ISSUE TITLE
ng-forward with jquery causes inconsistent event info

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#107]
When i throw an event with next:

* If i don't use jquery i can use $event.detail to get the data.
* If i use jquery i have to write $event.originalEvent.detail

I am not sure that it should be handled by ng-forward, but this means that if i add jquery for any reason i will have to go over my code and change many lines.

**Comment by timkindberg** [comment]
Because there is a way to have it work in both cases I'm not sure we'd take this on as a priority. So I'll close this. If it becomes an annoyance for enough people we can reopen it.

**Comment by MikeRyan52** [comment]
On the bright side, our CustomEvent dispatching seems flakey, and it may be worth switching to virtual events using jQLite/jQuery.

**Comment by timkindberg** [comment]
@MikeRyan52 you can reopen if you want.
