### ISSUE TITLE
New starter project

### ISSUE THREAD

**Issue by hannahhoward** [ngUpgraders/ng-forward#11]

**Comment by timkindberg** [comment]
I feel like the TodoMVC mostly completes this issue. It just needs tests, so we can show people how to test their code with our test util classes.

Also, I personally feel like we should be using webpack / babel in our starter project instead of browserify / babel. Or JSPM (but webpack is better). That one is preferential I guess though.

We could make new stories for starter tests and for moving to webpack or jspm.

Thoughts anyone?

**Comment by pbastowski** [comment]
Yeah, there are thoughts about this. Pawel Kozlowski gave a talk on bundling with the different tools available. It should be on YouTube now. I need to watch it again myself and then try a few different things before I'll decide for myself.

**Comment by pbastowski** [comment]
Here is the link http://youtu.be/9odY9Rh5kTQ

**Comment by timkindberg** [comment]
Here's some output size comparisons. Apparently there is a new kid on the block as well, rollup. Which is good for library authors.

https://github.com/nolanlawson/rollup-comparison

**Comment by timkindberg** [comment]
Sorry I guess that last comment is really more pertinent to a discussion around moving the actual ng-forward repo to something other than browserify.

**Comment by MikeRyan52** [comment]
There is already an excellent Webpack starting repo for Angular 2 that would work with a TypeScript ng-forward just fine: https://github.com/angular-class/angular2-webpack-starter

Additionally, Browserify is listed as one of the leading build tools by Angular 2 developers (behind Webpack and tied with SystemJS): http://angularjs.blogspot.com/2015/09/angular-2-survey-results.html

Given that there is already a Webpack boilerplate, I think we would offer something both unique and useful to teams that want to see examples of TypeScript+Babel+Browserify.

**Comment by timkindberg** [comment]
@MikeRyan52 ok and there's probably a lot of people coming from browserify still. Seeing as ng-forward is geared towards migrating, I think its good to keep our starter on browserify + gulp.

**Comment by timkindberg** [comment]
I'll make a new story for adding tests to the TodoMVC

**Comment by aciccarello** [comment]
@timkindberg Yes! Test examples would be very helpful.
