### ISSUE TITLE
Mixing ng 1.x with ng-forward code

### ISSUE THREAD

**Issue by misaizdaleka** [ngUpgraders/ng-forward#110]
Will you be able to for example, keep some code in the old ng 1.x format and use for the rest ng-forward approach? I'm asking because we have a very big application and wouldn't be able to migrate everything right away to the new syntax.

**Comment by timkindberg** [comment]
We have some ideas around this, the answer is basically yes, see this section of the FAQ: https://github.com/ngUpgraders/ng-forward#what-does-a-migration-from-regular-angular-1-code-to-ng-forward-code-look-like
