### ISSUE TITLE
Injectable any param needs to be optional

### ISSUE THREAD

**Issue by PLEEROCK** [ngUpgraders/ng-forward#114]
Created a simple project using Typescript and have lot of errors

*inject.d*
```export declare function Inject(...injects: any[]): (t1: any, name: string, {value: t2}?: {}) => void;```

what is "value" here? its wrong type/variable/whatever it is

*injectable.d*
```export declare const Injectable: (any) => any;```

what is "(any)" here? variable? it should be (any: any) at least, also it should be optional, since all examples are specifying ```@Injectable()``` without any parameter

**Comment by MikeRyan52** [comment]
Hi @PLEEROCK, my apologies. These issues have already been fixed in master but it has been a while since we've released a new alpha. I've gone ahead and published v0.0.1-alpha.11 which should fix the type errors you are getting.

Thanks!

**Comment by PLEEROCK** [comment]
updated, but I dont see @Injectable to be working. 

```export declare const Injectable: (any: any) => any;```

must be 

```export declare const Injectable: (any?: any) => any;```

otherwise compiler gives error because any is required but not providede

```typescript
@Injectable()
@Inject('$q')
class SomeComponent {
}
```

**Comment by timkindberg** [comment]
I fixed the additional issue. We'll need another release.

**Comment by aweiher** [comment]
As there was no release yet, how to use Injectable with parameters? How must "any" looks like in this case?

**Comment by aweiher** [comment]
Ok, found out that `@Injectable(undefined)` is totally valid
