### ISSUE TITLE
Errors building the source

### ISSUE THREAD

**Issue by tolemac** [ngUpgraders/ng-forward#116]
I'm trying to build the source an have some errors.

I have had to install Python and Ms Visual Studio C++ ... and now I'm getting these errors:

	[00:52:40] Requiring external module babel-core/register
	[00:52:41] Using gulpfile ~\Desarrollo\Angular\ng-forward\gulpfile.babel.js
	[00:52:41] Starting 'build'...
	[00:52:41] Starting 'clean-dist'...
	[00:52:41] Finished 'clean-dist' after 50 ms
	[00:52:41] Starting 'build/ts-to-es6'...
	error TS2318: Cannot find global type 'Array'.
	error TS2318: Cannot find global type 'Boolean'.
	error TS2318: Cannot find global type 'Function'.
	error TS2318: Cannot find global type 'IArguments'.
	error TS2318: Cannot find global type 'Iterable'.
	error TS2318: Cannot find global type 'IterableIterator'.
	error TS2318: Cannot find global type 'Iterator'.
	error TS2318: Cannot find global type 'Number'.
	error TS2318: Cannot find global type 'Object'.
	error TS2318: Cannot find global type 'RegExp'.
	error TS2318: Cannot find global type 'String'.
	error TS2318: Cannot find global type 'Symbol'.
	error TS2318: Cannot find global type 'TemplateStringsArray'.
	error TS2468: Cannot find global value 'Symbol'.
	lib\classes\metastore.ts(46,52): error TS4073: Parameter 'callbackFn' of public method from exported class has or is using private name 'Map'.
	lib\classes\module.ts(77,13): error TS4055: Return type of public method from exported class has or is using private name 'ng'.
	lib\classes\provider.ts(23,41): error TS4063: Parameter 'token' of constructor from exported class has or is using private name 'Function'.
	lib\decorators\state-config.ts(7,17): error TS4000: Import declaration 'IState' is using private name 'ng'.
	lib\properties\outputs-builder.ts(15,75): error TS4078: Parameter '$scope' of exported function has or is using private name 'ng'.
	lib\testing\test-component-builder.ts(7,27): error TS4000: Import declaration 'IInjectorService' is using private name 'angular'.
	lib\testing\test-component-builder.ts(52,40): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
	lib\testing\test-component-builder.ts(101,24): error TS4063: Parameter '{
			debugElement,
			rootTestScope,
			$injector
		  }' of constructor from exported class has or is using private name 'ng'.
	lib\util\helpers.ts(42,68): error TS4078: Parameter 'ngModule' of exported function has or is using private name 'ng'.
	lib\util\jqlite-extensions.ts(4,27): error TS4000: Import declaration 'IAugmentedJQuery' is using private name 'angular'.
	lib\util\jqlite-extensions.ts(5,33): error TS4000: Import declaration 'IAugmentedJQueryStatic' is using private name 'angular'.
	lib\util\jqlite-extensions.ts(13,10): error TS4067: Parameter 'func' of call signature from exported interface has or is using private name 'Function'.
	[00:52:44] TypeScript: 14 global errors
	[00:52:44] TypeScript: 12 emit errors
	[00:52:44] TypeScript: emit succeeded (with errors)
	[00:52:44] Finished 'build/ts-to-es6' after 2.97 s
	[00:52:44] Starting 'build/test'...
	adding C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\angular-mocks\angular-mocks.js
	11 12 2015 00:52:49.578:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.580:ERROR [framework.browserify]: Error: Cannot find module './classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:49.584:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.584:ERROR [framework.browserify]: Error: Cannot find module './classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:49.586:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.587:ERROR [framework.browserify]: Error: Cannot find module './test-component-builder' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\testing'
	11 12 2015 00:52:49.593:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
	11 12 2015 00:52:49.598:INFO [launcher]: Starting browser Chrome
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: Error: Cannot find module './provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\classes'
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: Error: Cannot find module '../classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.608:ERROR [framework.browserify]: Error: Cannot find module '../classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: Error: Cannot find module './module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\classes'
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: Error: Cannot find module './provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\classes'
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.613:ERROR [framework.browserify]: Error: Cannot find module './state-config' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:49.618:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.618:ERROR [framework.browserify]: Error: Cannot find module './helpers' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\util'
	11 12 2015 00:52:49.618:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:49.618:ERROR [framework.browserify]: Error: Cannot find module '../classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\util'
	11 12 2015 00:52:51.378:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.379:ERROR [framework.browserify]: Error: Cannot find module './classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.380:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.380:ERROR [framework.browserify]: Error: Cannot find module './classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.381:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.382:ERROR [framework.browserify]: Error: Cannot find module './classes/metastore' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.382:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.383:ERROR [framework.browserify]: Error: Cannot find module './classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.384:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.384:ERROR [framework.browserify]: Error: Cannot find module './decorators/state-config' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.385:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.385:ERROR [framework.browserify]: Error: Cannot find module './util/jqlite-extensions' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.387:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.387:ERROR [framework.browserify]: Error: Cannot find module './classes/metastore' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib'
	11 12 2015 00:52:51.388:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.389:ERROR [framework.browserify]: Error: Cannot find module '../util/helpers' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.390:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.390:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.392:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.392:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.394:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.395:ERROR [framework.browserify]: Error: Cannot find module './test-component-builder' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\testing'
	11 12 2015 00:52:51.438:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.439:ERROR [framework.browserify]: Error: Cannot find module '../util/jqlite-extensions' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\tests'
	11 12 2015 00:52:51.439:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.440:ERROR [framework.browserify]: Error: Cannot find module '../testing/test-component-builder' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\tests'
	11 12 2015 00:52:51.441:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.442:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.442:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.442:ERROR [framework.browserify]: Error: Cannot find module '../util/helpers' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.442:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.442:ERROR [framework.browserify]: Error: Cannot find module '../classes/module' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\decorators'
	11 12 2015 00:52:51.447:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.447:ERROR [framework.browserify]: Error: Cannot find module '../classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\testing'
	11 12 2015 00:52:51.447:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.447:ERROR [framework.browserify]: Error: Cannot find module '../util/helpers' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\events'
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: Error: Cannot find module '../properties/outputs-builder' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\util'
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: Error: Cannot find module './helpers' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\util'
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: bundle error
	11 12 2015 00:52:51.452:ERROR [framework.browserify]: Error: Cannot find module './../classes/provider' from 'C:\Users\Javier\Desarrollo\Angular\ng-forward\dist\lib\util'
	11 12 2015 00:52:51.505:INFO [Chrome 47.0.2526 (Windows 10 0.0.0)]: Connected on socket TzaCMxIMgtDAFyY9AAAA with id 8332007
	Chrome 47.0.2526 (Windows 10 0.0.0) ERROR
	  You need to include some adapter that implements __karma__.start method!
	Chrome 47.0.2526 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.274 secs / 0 secs)
	[00:52:52] 'build/test' errored after 7.62 s
	[00:52:52] Error: 1
		at formatError (C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js:169:10)
		at Gulp.<anonymous> (C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js:195:15)
		at emitOne (events.js:82:20)
		at Gulp.emit (events.js:169:7)
		at Gulp.Orchestrator._emitTaskDone (C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\orchestrator\index.js:264:8)
		at C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\orchestrator\index.js:275:23
		at finish (C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\orchestrator\lib\runTask.js:21:8)
		at cb (C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\orchestrator\lib\runTask.js:29:3)
		at removeAllListeners (C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\karma\lib\server.js:332:7)
		at Server.<anonymous> (C:\Users\Javier\Desarrollo\Angular\ng-forward\node_modules\karma\lib\server.js:343:9)
		at Server.g (events.js:260:16)
		at emitNone (events.js:72:20)
		at Server.emit (events.js:166:7)
		at emitCloseNT (net.js:1521:8)
		at doNTCallback1 (node.js:441:9)
		at process._tickCallback (node.js:363:17)
	[00:52:52] 'build' errored after 11 s
	[00:52:52] Error in plugin 'run-sequence'
	Message:
		An error occured in task 'build/test'.

Any ideas?
Thanks in advance.

**Comment by david-gang** [comment]
I am just guessing. Maybe try to run 
>npm install 
and then 
>npm test

If this does not work, maybe provide the node and npm version you are running

**Comment by tolemac** [comment]
Thanks you @david-gang, after *npm test* I can build the sources.

I continue getting some errors:

	[09:09:11] Starting 'build/ts-to-es6'...
	error TS2318: Cannot find global type 'Boolean'.
	error TS2318: Cannot find global type 'IArguments'.
	error TS2318: Cannot find global type 'Iterable'.
	error TS2318: Cannot find global type 'IterableIterator'.
	error TS2318: Cannot find global type 'Number'.
	error TS2318: Cannot find global type 'Symbol'.
	error TS2318: Cannot find global type 'TemplateStringsArray'.
	error TS2468: Cannot find global value 'Symbol'.
	[09:09:14] TypeScript: 8 global errors
	[09:09:14] TypeScript: emit succeeded (with errors)
	[09:09:15] Finished 'build/ts-to-es6' after 3.51 s

but I can build it.

Thanks!!!

**Comment by eXaminator** [comment]
I think you also need to install typescript and do `tsd install`.

For some reason I haven't seen this documented anywhere.

**Comment by timkindberg** [comment]
@tolemac problem solved? If not, reopen.

**Comment by tolemac** [comment]
Yep! solved!
