### ISSUE TITLE
kebab case removal in angular2

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#118]
Hi all,

I am sure this has a big impact on us.

https://github.com/angular/angular/commit/da9b46a

We have to discuss this,

**Comment by panjiesw** [comment]
Hi,
I've been using ng-forward for my new project to ease the upgrade to `angular2` when it's released. You guys have done terrific job on it.

As far as I understand, ng-forward still uses all features from `angular 1`. So i think at least, from the removal of kebab case in `angular2`, especially for the built-in directives (`ngIf`, `ngFor`, etc.), it'll be hard to implement on top of `angular 1`. Unless they decided to also implement the camel case directive in `1.5.x`.

We can still force the use of camel case in component's properties, but for built in directive it'll be a manual upgrade/refactoring for users who want to use `angular2` in the future.

Or is it really possible to implement in ng-forward?

**Comment by timkindberg** [comment]
@panjiesw thank you! We really appreciate the kind words.

@petebacondarwin didn't we figure this out. We just can't support it right? Or can we?

**Comment by MikeRyan52** [comment]
Yeah, we talked about this in one of our meetings a couple of months back and determined that it wouldn't be feasible to support it in ng-forward. Unfortunately, the decision to use case-sensitive attributes is out-of-spec, meaning we would need our own HTML parser just as they do :cry:

**Comment by timkindberg** [comment]
Thanks @MikeRyan52, so let's close this then...
