### ISSUE TITLE
Dynamically Loading / Lazy Loading Components

### ISSUE THREAD

**Issue by micahlee** [ngUpgraders/ng-forward#121]
I have an angular 1 application that dynamically loads element directives with systemjs to lazily compile and render after the initial application loads and bootstraps. I do this now by capturing the $compileProvider when I create the module, and then I use it later to register directives as they're loaded with system.js so that I can use $compile to render them from within a parent component directive.

Is there a proper way to do something like this with ng-forward? I see in angular 2 there is a DynamicComponentLoader, but I don't know enough about it to know if it's actually relevant to this or if there is an ng-forward equivalent. 

Thanks for the hard work! I've been very impressed with how easy it's been to start moving existing angular 1 code over to start getting prepared for angular 2. :+1:

**Comment by timkindberg** [comment]
So the "proper" way in ng-forward would be however we would have to do it in Angular 2. If you could do the research to find the canonical Angular 2 way of doing this, then we can slot a story that adds the functionality to ng-forward. Since it's clearly possible in angular 1, it's just a matter of putting the correct facade over top of it.

**Comment by micahlee** [comment]
Sorry for the delay. After a little more reading, it looks like DynamicComponentLoader is the way to go in Angular 2. I'll try to put something together that achieves the goal in angular 1 and 2 as a comparison. 

Also, as a side note, I am able to workaround my issue right now by performing the dynamic loading in a angular 1 module that is just an additional named provider for the ngForward components.

**Comment by timkindberg** [comment]
Awesome, if you could post your example for others looking in the future that would be great!!

**Comment by heiso** [comment]
Hi there :) 
@micahlee 
> Also, as a side note, I am able to workaround my issue right now by performing the dynamic loading in a angular 1 module that is just an additional named provider for the ngForward components.

Is your workaround still relevant ? Should be awesome to look at an example :)

**Comment by micahlee** [comment]
Closing as no longer relevant
