### ISSUE TITLE
using <content></content> inside a component template

### ISSUE THREAD

**Issue by jeevandark** [ngUpgraders/ng-forward#126]
Hi,
Is the above possible?
I mean, using <pre>&lt;content&gt;&lt;/content&gt;</pre> inside a component template written with ng-forward - to enable the consumer insert the content he wants inside the component?
(I could not make it happen)

eg. - in the template:  
@Component ({
    selector: 'my-element',
    template: &apos;&lt;content&gt;&lt;/content&gt;&apos;
})

and in the consuming html:
&lt;my-element&gt;
      &lt;span class='any-class'&gt;PRESS ME&lt;/span&gt;
&lt;/my-element&gt;

Why? any other way to achieve that with ng-forward?

**Comment by timkindberg** [comment]
That's already supported. Have you tried it?

**Comment by jeevandark** [comment]
Hi
Thanks a lot for the quick reply!


Will try to upgrade to alpha-11  (from alpha-8)  and see if that helps..  :)

10x again
