### ISSUE TITLE
Error in docs about testing using TestComponentBuilder?

### ISSUE THREAD

**Issue by jasonmacdonald** [ngUpgraders/ng-forward#136]
I think there might be an error in the docs about testing. It says to import TestComponentBuilder from 'ng-forward', but that returns a "cannot resolve symbol' error. I checked and the index.d.ts does not import that file. It seems I have to import it from 'ng-forward/cjs/testing'. Is this correct, or did I do something wrong?

Here's a quick example. The first import gives an error, the second one doesn't.

```
import {Component, TestComponentBuilder} from 'ng-forward';
import {TestComponentBuilder} from 'ng-forward/cjs/testing';
import {Home} from './home';

// Instantiate the Builder, this part is different than ng2.
// In ng2 you inject tcb.
const tcb = new TestComponentBuilder();

// Create your test bed
@Component({ selector: 'test-cmp')
class Test {}

describe('Home', () => {
    it('should have name', () => {
        let html = '<home></home>';

        // Use tcb to override templates and providers, then create your fixture.
        tcb
            .overrideTemplate(Test, html)
            .createAsync(Test).then(fixture => {
            let homeComp = fixture.componentInstance;
            expect(homeComp.name).toEqual('Home');
        });
    });
})
```

**Comment by timkindberg** [comment]
You are right! I'll fix it. You might be able to import from 'ng-forward/testing' as well.

**Comment by jasonmacdonald** [comment]
Damn, you're fast. I was still editing my post lol.

**Comment by jasonmacdonald** [comment]
Found another error in the docs. :( Inside the createAsync callback, you must call done(); (since it's an async call) or Jasmine will always return "true" for your expectation. Also, need to add variable "done" to the "it" call to gain access to the done method...

```
it('should have name', (done) => {
        let html = '<home></home>';

        // Use tcb to override templates and providers, then create your fixture.
        tcb
            .overrideTemplate(Test, html)
            .createAsync(Test).then(fixture => {
            let homeComp = fixture.componentInstance;
            expect(homeComp.name).toEqual('Home');
            done();
        });
    });
```

**Comment by timkindberg** [comment]
Yup you are right.
