### ISSUE TITLE
Can't get ng-for to work

### ISSUE THREAD

**Issue by reflog** [ngUpgraders/ng-forward#147]
Is there anything special I should do so that code like this:
```
<span *ng-for="#pass in ctrl.pass">{{pass}}</span>
<input [value]="ctrl.pass">
```
will work?
For now, it just generates this node:
```
<span ng-for="#pass in ctrl.pass" class="ng-binding"></span>
<input [value]="ctrl.pass">
```
but doesn't actually bind it

**Comment by timkindberg** [comment]
We've not polyfills ngFor. Please use Ng-repeat.
