### ISSUE TITLE
Building ngFutureProof

### ISSUE THREAD

**Issue by Successful** [ngUpgraders/ng-forward#148]
Hi, I am trying to build a future proof skeleton using angular 1.x, ES6 and typescript.

Using JSPM/SystemJS trying to implement ng-forward to make it future proof. 
I have noticed that there is a lack of documentation using the components I have in my project, so i cant get my project to build without errors.

I would really appreciate if i could get some help making my project build-able. I you guys want you can use this skeleton as a reference/example when building ng-forward.

So please contribute and help me out:
[ngFutureProof](https://github.com/Successful/ngFutureProof)

**Comment by guybedford** [comment]
I'd suggest starting with an already-working boilerplate if you can, preferably using the typescript plugin https://github.com/frankwallis/plugin-typescript.

**Comment by Successful** [comment]
guybedford, i see what you mean, this boilerplate is from a working repository called [ts-skeleton](https://github.com/b091/ts-skeleton) I started to get really big issues when i tried to implement ng-forward to make it future proof with decorators.

Having problem to find the module, don't know if it jspm, ng-forward or the compiler that causes the error.

The important with this project is that i want to feel like angular 2, so that i easily can update.
