### ISSUE TITLE
Add set of core [property] directives for visible, disabled, etc

### ISSUE THREAD

**Issue by MikeRyan52** [ngUpgraders/ng-forward#15]
With property bindings, we should probably add a list of core directives for common element properties. I know there is a list somewhere of native properties supported in the Angular 2 codebase.

Covers scenarios like:

```html
<input type="text" [disabled]="myComponent.disabled">
```

**Comment by timkindberg** [comment]
I think this is a duplicate of #5. Reopen if not.

**Comment by timkindberg** [comment]
Or perhaps its for the element's properties that are in addition to ones from #5?
