### ISSUE TITLE
ngResource ngAnimate plans

### ISSUE THREAD

**Issue by Guardiannw** [ngUpgraders/ng-forward#150]
From what I can tell, it doesn't look like there is any ng-forward support for these angular modules?  Is this true, or are there any future plans to implement them?  If not, what is the best way to go about implementing them in the application?

Thanks,

**Comment by timkindberg** [comment]
They are supported. Import them then tell the providers to load the module
similar to our uirouter example.

providers: ['ngResource', 'ngAnimate']
On Wed, Feb 17, 2016 at 10:18 AM Nathan Webb <notifications@github.com>
wrote:

> From what I can tell, it doesn't look like there is any ng-forward support
> for these angular modules? Is this true, or are there any future plans to
> implement them? If not, what is the best way to go about implementing them
> in the application?
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ngUpgraders/ng-forward/issues/150>.
>
-- 
- Tim

**Comment by Guardiannw** [comment]
Ok, thanks.
