### ISSUE TITLE
Required  a way to test the component with Input and Output

### ISSUE THREAD

**Issue by erashu212** [ngUpgraders/ng-forward#151]
Hi,

Can anybody please suggest how can I do a component testing with Input and Output in Mocha + Sinon + Chai.

Thanks,
Ashutosh

**Comment by timkindberg** [comment]
See the docs: https://github.com/ngUpgraders/ng-forward/blob/master/API.md#testing

Also see: https://github.com/ngUpgraders/ng-forward-playground/blob/feat/tests/app/components/FilterLinks.spec.js

See how the test injects the controller via the `componentInstance` property? You can access your inputs and trigger your outputs via there.

**Comment by erashu212** [comment]
Can you please provide some kind of snippet. Actually I am lost.
