### ISSUE TITLE
AsyncRoute for ng-forward

### ISSUE THREAD

**Issue by shripalsoni04** [ngUpgraders/ng-forward#153]
Is there a way in ng-forward to load the route components dynamically similar to [AsyncRoute](https://angular.io/docs/ts/latest/api/router/AsyncRoute-class.html) in angular 2.

And :+1:  for developing awesome ng-forward library.

**Comment by timkindberg** [comment]
Thanks! As of right now there isn't and currently no plans to implement. It's just not something that is easily supported in Angular 1 without hacks. You can look at implementing it yourself with something like https://oclazyload.readme.io/ or https://christopherthielen.github.io/ui-router-extras/#/future. But the usage would be up to you and you'd probably be writing code that looks very Angular 1-ish.
