### ISSUE TITLE
attribute binding

### ISSUE THREAD

**Issue by vonbrana** [ngUpgraders/ng-forward#160]
I have tried using ng-forward with simple attribute binding:

&lt;div [hidden] = 'true' &gt; it's hidden &lt;/div&gt;

But this does not work.  Should this work or is this something that is still coming?

Also I notice that there has been little activity on this repo since January.  Has work been discontinued?

**Comment by timkindberg** [comment]
At this time work has been discontinued. Both core contributors, myself and
Mike, are deeply engaged in our jobs even during evening hours and cannot
find time at the moment for this project.

The original goal for this project was achieved; to allow ng1 development
to mimic ng2. As ng2 nears completion most folks will migrate. There are a
couple bugs pertaining to migration that need to be addressed, however
other than those I don't think we will see any more major development in
this project.

Mike and I are happy to hand the project over to someone who may want to
drive it forward. Contact us if interested.
On Mon, Apr 11, 2016 at 10:05 AM vonbrana <notifications@github.com> wrote:

> I have tried using ng-forward with simple attribute binding:
> it's hidden
>
> But this does not work. Should this work or is this something that is
> still coming.
>
> Also I notice that there has been little activity on this repo since
> January. Has work been discontinued?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ngUpgraders/ng-forward/issues/160>
>
-- 
- Tim

**Comment by timkindberg** [comment]
@MikeRyan52 any thoughts you might want to add?

**Comment by vonbrana** [comment]
Thanks for the answer.  The project is very interesting and has accomplished a lot.  Too bad it must stop for the time being.  The one thing that would prevent me from near total migration to angular 2 syntax  of a couple simple angular projects we have in production is the attribute binding.  But, still it does go a far way to preparing for eventual migration.
