### ISSUE TITLE
Ping!

### ISSUE THREAD

**Issue by dsebastien** [ngUpgraders/ng-forward#161]
Hey there,

I'm just creating this issue to know if ng-forward is still alive, know a bit more about its status etc.
Are there still plans to move this.. forward? :)

**Comment by MikeRyan52** [comment]
Hi @dsebastien, [see here for details](https://github.com/ngUpgraders/ng-forward/issues/160#issuecomment-208637771) regarding the status of ng-forward

**Comment by dsebastien** [comment]
@MikeRyan52 Thanks for the quick answer :)
