### ISSUE TITLE
Roadmap for ng-forward

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#174]
Hi all,

I know that this project is abandoned.
Nevertheless  I have an important project written in this.
Migrating to ng-metadata is a too big change at this time. I want to maintain the module even in a minimal state, so that i could upgrade easily to angular 2 when the ecosystem is more stable( angular 2 material, ...).
I want to get quick gains from making small changes:
- First of all, we need not to have breaking changes here. Therefore i would like to reset the branch to the tag 0.12 alpha. I did it already in my fork. This will enable us to make PRs
- Upgrade to the latest rxjs beta. I think that using two different rxjs versions would be problematic. Therefore why not upgrading to a later and greater version?
- Use a component polyfill like https://github.com/toddmotto/angular-component
  This would give us the ability to change the input map creation which causes fails in angular2 ngupgrade and also would open us the same interface as angular1 conmponent.

I could spend limited time but will need mentorship from the core contributors.
@timkindberg or @MikeRyan52 : What do you think regarding these issues.
Could you guide me in these?

Thanks,
David

**Comment by timkindberg** [comment]
David, I also have a large project built on top of an ng2 polyfill (a1atscript) so I sympathize with you. Both that project and this one are no longer actively developed, but luckily they are mostly stable. 

I can't speak for @MikeRyan52 but I will only be able to provide limited guidance and probably almost no help with actual coding work. I'm happy to read issues or comments and see if I can help with the limited time I have though.

I think your goals are good though, to do as little work as possible and keep things stable.
