### ISSUE TITLE
Event emitters and custom events

### ISSUE THREAD

**Issue by MikeRyan52** [ngUpgraders/ng-forward#3]
I have a spike put together for semi-dynamic events: https://github.com/ngUpgraders/ng-forward/blob/master/src/util/events.js

When you declare custom events on your component, a special `[on-${event}]` directive is created. These onEvent directives function similarly to the existing `[ng-${event}]` directives. Two questions:

1. Do we like this approach for custom events?
2. Do we provide component controllers with an [event emitter similar to Angular 2](https://github.com/angular/angular/blob/2.0.0-alpha.32/modules/angular2/src/facade/async.ts#L89-L128)?

**Comment by egor-smirnov** [comment]
1. I like it.
2. Could you explain this a bit more? Not sure that I understand what is meant here.

**Comment by MikeRyan52** [comment]
Sure, I went ahead and spiked it out: https://github.com/ngUpgraders/ng-forward/tree/spike/events-and-properties

Basically the event emitter lets you easily dispatch events to your component. Example using the above branch:

```js
import {Component} from 'ng-forward';

@Component({
  selector: 'my-component',
  properties: ['custom']
})
class MyComponent{
  constructor(){
    setInterval(() => this.CustomEmitter.onNext({ }), 500); // Triggers 'custom' event on the element
  }
}
```

**Comment by pbastowski** [comment]
@MikeRyan52 It sounds interesting. Do you have a practical use-case for this? Perhaps something you've worked on already.

 I'm trying to think how I could use this in my apps.

**Comment by MikeRyan52** [comment]
So the core of the idea is honestly to mimic Angular 2 component events as closely as possible. The above in Angular 2 looks like:

```js
import 'reflect-metadata';
import 'zone.js';
import {Component, View, EventEmitter, bootstrap} from 'angular2/angular2';

@Component({
  selector: 'my-component',
  events: ['custom']
})
@View({ template: 'Hi!' })
class MyComponent{
	custom = new EventEmitter();
  constructor(){
    setInterval(() => this.custom.next({ }), 500); // Triggers 'custom' event on the element
  }
}

@Component({ selector: 'app' })
@View({
  template: '<my-component on-custom="onCustom()"></my-component>',
  directives: [MyComponent]
})
class App{
  onCustom(){
    console.log('triggered');
  }
}

bootstrap(App);
```

In your apps, any time you used the `&` scope binding you would want to use these events instead.

**Comment by MikeRyan52** [comment]
After spending some more time with the Angular 2 implementation, I've updated the spike to more closely resemble Angular 2 events.

**Comment by egor-smirnov** [comment]
@MikeRyan52 Wow, thank you for fast response and even faster implementation. Looks awesome! I like this EventEmitter, if possible would be nice to have EventEmitter.
