### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by daniele-zurico** [ngUpgraders/ng-forward#31]
Is possible to have that in Typescript?

**Comment by waeljammal** [comment]
I second this, it's unusable in TS, I tried to convert it but too many issues, tried to build and minify the JS and import it but could not minify due to syntax errors as well.

**Comment by timkindberg** [comment]
We are definitely still in alpha. We've not put as much thought into the build/dist solution as we need to yet. Please check back soon though!

**Comment by waeljammal** [comment]
Thanks

**Comment by reppners** [comment]
Is the conversion already in progress? I could take a stab at it and provide a PR to get the conversion started.

**Comment by timkindberg** [comment]
I think @MikeRyan52 is working on it. There might be other stuff you could take a stab at...

**Comment by MikeRyan52** [comment]
I am indeed working on it. Hoping to have something ready to demo here in the next week.

**Comment by MikeRyan52** [comment]
For what it is worth, we have a branch now of ng-forward [written in TypeScript](https://github.com/ngUpgraders/ng-forward/tree/typescript) so progress is being made on this.
