### ISSUE TITLE
equivalent of module.config and module.run

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#35]
Hi,

What is the equivalent of module.config and module.run function?
For example, where do i configure the $stateProvider of the ui-router. In the traditional angular1 syntax i configure it in the config function.

Thanks,
David

**Comment by MikeRyan52** [comment]
No equivalent right now for those in ng-forward, though we would love to hear suggestions on how we could integrate it into ng-forward.

If you are already using the library and need a quick workaround, the key is to remember that `@Component` providers can take a classic `angular.module` letting you do something like this:

```js
angular.module('my-app.config', []).config(() => {});

@Component({
  selector: 'my-app',
  providers: ['my-app.config']
})
class MyApp{ }

bootstrap(MyApp);
```

**Comment by MikeRyan52** [comment]
In response to #36:

In Angular 2, config happens through the DI system. For example, If you want to swap out the HttpBackend for Http you would create a new provider for it. This would be a little too difficult to shim in Angular 1 and it wouldn't work with classic Angular 1 modules. I do like the idea of an `@Config` decorator in this case.

As for run time, I believe in Angular 2 the `bootstrap` function returns a promise that resolves with the root injector. This could be an option for ng-forward.

**Comment by reppners** [comment]
@david-gang Thx for the pointer ;) ng-forward has an undocumented decorator for configuring ui-router https://github.com/ngUpgraders/ng-forward/blob/master/src/decorators/providers/state-component.js

But notice MikeRyan52's comment:
https://github.com/ngUpgraders/ng-forward/issues/34#issuecomment-150921169

@MikeRyan52 
My suggestion is to have a Config-decorator so users just don't have to deal with modules if they don't want to. Though it should be made obvious to everyone migrating that Config is not part of ng2.

I am in the process of migrating from angular-decorators to ng-forward so I don't know yet how well it will work out but I will report any problems.

**Comment by david-gang** [comment]
Thanks @reppners

**Comment by reppners** [comment]
Since the conversion to TypeScript is on its way and I was not able to come up with an implementation on my own I just wanted to document my proposal for a config/run decorator.

I converted a code-base with several config-blocks to ng-forward and came to the conclusion that a decorator on a `function` would be most useful since I have config-blocks belonging to services and components.

```TS
@Injectable()
class MyService {

  @Inject("someProvider")
  static config(someProvider) {
    ...
  }
}
```

**Comment by MikeRyan52** [comment]
I like this version. It is consistent with how we do the link and compile functions for directives.

**Comment by PLEEROCK** [comment]
I think simply need to introduce method annotation to a component class

```typescript
@Component({
  selector: 'my-app',
  providers: ['someProvider']
})
class MyApp{ 

  constructor(someProvider: any) {
  }

  @Config()
  configOneStuff() {
    ...
  }
  @Config()
  configAnotherStuff() {
    ...
  }

  @Run()
  runOneStuff() {
    ...
  }

  @Run()
  runAnotherStuff() {
    ...
  }

}
```
