### ISSUE TITLE
Decorator for module.config()

### ISSUE THREAD

**Issue by reppners** [ngUpgraders/ng-forward#36]
I am wondering if it makes sense to provide a decorator for the ng1 config phase. AFAIK in ng2 the config phase doesn't exist so a decorator might just be there for migration. 

Right now all config stuff would be moved to the the nearest top module where it would be appropriate to `bundle()` a module. I'd rather like to have a solution where the config code stays close to the service it belongs to. On the other hand I'm a bit confused what will happen to all this config-code in ng2? Where will this kind of things happen?

**Comment by david-gang** [comment]
Connected to #35 :-)

**Comment by reppners** [comment]
Closing this in favor of having just one issue open about this :)
