### ISSUE TITLE
Not working with jspm/SystemJS

### ISSUE THREAD

**Issue by reppners** [ngUpgraders/ng-forward#37]
Tried to get this working with jspm but can't figure out a way to make it run.

jspm-config-override
```
"npm:ng-forward@0.0.1-alpha.4": {
        "peerDependencies": {
          "angular": "^1.4.0"
        },
        "shim": {
          "dist/index": [
            "angular"
          ]
        }
      }
```
results in
```
Uncaught Uncaught TypeError: Object.defineProperty called on non-object
	Evaluating http://localhost:8081/jspm_packages/npm/ng-forward@0.0.1-alpha.4/dist/index.js
	Evaluating http://localhost:8081/jspm_packages/npm/ng-forward@0.0.1-alpha.4.js
	Error loading http://localhost:8081/bootstrap.js
  (anonymous function)	
```
because the way jspm loads it, there is no `exports` defined.

If I don't specify the angular dependency as shim config
```
"npm:ng-forward@0.0.1-alpha.4": {
        "peerDependencies": {
          "angular": "^1.4.0"
        }
      }
```
there is no global `angular` there
```
Uncaught Uncaught Uncaught ReferenceError: angular is not defined
	Evaluating http://localhost:8081/jspm_packages/npm/ng-forward@0.0.1-alpha.4/dist/util/jqlite-extensions.js
	Evaluating http://localhost:8081/jspm_packages/npm/ng-forward@0.0.1-alpha.4/dist/index.js
	Evaluating http://localhost:8081/jspm_packages/npm/ng-forward@0.0.1-alpha.4.js
	Error loading http://localhost:8081/bootstrap.js
  (anonymous function)	
```

So maybe I'm just missing the obvious here, but shouldn't `ng-forward` explicitly import angular when it needs angular instead of relying on it being there as a global?

**Comment by reppners** [comment]
Found a few hints on why there are problems. 

So the `shim`-config I think is the "right" way to do it, but then SystemJS/jspm treats ng-forward as a global module, which leads to `exports` not being defined. Good news is: jspm 0.17 will respect the jspm/override configuration so a setting like

```
"jspm": {
    "format": "cjs",
    "shim": {
      "dist/index": {
        "deps": [
          "angular"
        ]
      }
    }
  }
```
will work then.

Until jspm 0.17 is out we'll have to resort to directly configuring meta-data in the system.config:
```
meta: {
    "ng-forward/dist/index": {
      "format": "cjs",
      "deps": [
        "angular"
      ]
    }
  }
```

See https://github.com/jspm/jspm-cli/issues/1037

**Comment by MikeRyan52** [comment]
Looking into this further, the assumption that Angular is global is deliberate to support users with a more traditional setup (ES5 with minimal build step). This is a similar assumption the "core" packages make, like angular-aria or angular-animate. Wouldn't you have to perform a similar trick for these packages?

**Comment by reppners** [comment]
Yes, you are right about the global angular. However there seems to be no special configuration needed for those angular core packages when using them with jspm/SystemJS. It just works. 

It's worth noting that when installing angular via jspm the [bower/npm repo](https://github.com/angular/bower-angular) is fetched. Looking at the [jspm-registry](https://github.com/jspm/registry) there is no special config-override present for the angular core repos.

The key thing seems to be that angular should be present as a dependency in the `package.json` so jspm knows it has to load it up front.

**Comment by yvess** [comment]
I made a test project see https://github.com/yvess/tests/tree/master/ng-forward-jspm, it worked for me in alpha.4 but doesn't work now in alpha.7

The error is `Error: View is not a function`

**Comment by timkindberg** [comment]
View is removed. Put everything into @Component.

**Comment by yvess** [comment]
works with @View removed :-), I also added an IE9 compatible build in my test project. Works for me now. 
Can be closed for me. @reppners it's working now for you?

**Comment by reppners** [comment]
@yvess yes, its working now :+1:
