### ISSUE TITLE
uninformative error message when provider is not valid

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#38]
Hi all,

I get the following error message:
"Uncaught Error: One or more of your providers was not valid. Please make sure all providers are either: a class, decorated class, Provider instance, or module string"

"groupModulesAndProviders	@	group-modules-providers.js:34
bundle	@	bundle.js:70
391../prmMissingTranslationHandler.factory	@	prmTranslate.module.ts:7
s	@	_prelude.js:1
(anonymous function)	@	_prelude.js:1
294../appConfig/appConfig.module	@	app.ts:10
s	@	_prelude.js:1
e	@	_prelude.js:1
(anonymous function)	@	_prelude.js:1"

This is too unspecific.

I need to know which provider had the problem.

**Comment by MikeRyan52** [comment]
Agreed. I believe Angular 2 does something like `Unknown providers [...] in MyComponent: [ MyService, MyFactory, undefined ]`

**Comment by david-gang** [comment]
I will try to take a look at it.

**Comment by timkindberg** [comment]
I'd looked at making that better and I think it was going to require passing more info to the `groupModulesAndProviders` function strictly for error messaging. Which I think is fine.

**Comment by david-gang** [comment]
Is there a way to reproduce the case through karma?
Do you have an example of how to configure thIs?

**Comment by timkindberg** [comment]
You used to be able to pass non-annotated classes, now if you have a naked class it will throw this error. So we need to remove the 'a class' part of the message. 

Something like this would be the test for it:

```js
it('should throw error when invalid module or provider in providers array', function(){
    class InvalidDueToNoAnnotations{ }

    expect(() => {
        groupModulesAndProviders([InvalidDueToNoAnnotations]);
    }).to.throw;
  });
```
