### ISSUE TITLE
How to troubleshoot ng-forward 

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#39]
Ng-forward does a lot behind the scenes.
When things don't work out as expected it may be hard to understand what the problem is.
I wanted to discuss how to tackle the troubleshoot

**Comment by david-gang** [comment]
There are two options which come to my mind.
A trouble shooting section with common pitfalls. A debugging mode where ng-forward explains what he is doing.
What do you think about this?

**Comment by timkindberg** [comment]
I like both ideas.

**Comment by timkindberg** [comment]
I'm going to close this. If you have time to write up a more detailed proposal for each idea (or better yet just do them and submit a PR!) we can discuss it further there. We want to keep things clean on github since it's likely that we'll be getting a lot of action.
