### ISSUE TITLE
Add source map to build bundle 

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#40]
The resulting JavaScript file of the build comes without source maps
Would be great to add this

**Comment by MikeRyan52** [comment]
We're close to having this in the new TS build.

**Comment by timkindberg** [comment]
@MikeRyan52 do we have this yet?

**Comment by MikeRyan52** [comment]
We're generating source maps now but I've gotten reports that they are corrupted.

**Comment by david-gang** [comment]
Hi,

If i compare the cjs folder to other projects(rxjs). I see that they have .map files, In ng-forward they are missing.

Maybe this info is helpful for you.

BR,
David
