### ISSUE TITLE
 ng-for for ng-forward :-)

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#43]
Is ng-for available ?
If not would it be possible to create this ?

**Comment by caseyhoward** [comment]
What do you mean exactly?

**Comment by david-gang** [comment]
I mean the ng-for of angular2
https://angular.io/docs/ts/latest/api/core/NgFor-directive.html

**Comment by timkindberg** [comment]
I just realized we could probably support this as a template preprocessor. Basically you could write the ng2 style and we'd use regex to convert it to ng1 style. So in output like chrome dev tools it would look like ng1. But you'd still get the benefit of easier migration. @david-gang thoughts?

**Comment by david-gang** [comment]
@timkindberg This would be a good idea.
I have a couple of questions:
How is this different from the kebab case issue? Also there we could run a regexp?
Additionally how can we be sure that we won't break anything. Once we do it wrong the pwerson would not be able to bootstrap his app.
