### ISSUE TITLE
Errors when using babel

### ISSUE THREAD

**Issue by waeljammal** [ngUpgraders/ng-forward#45]
Edited: I removed the previous issue as I solved it, however I have a new one.

I have module.provider() that I use to wrap JS libraries and make them injectable. I can not figure out how to use provider in ng-forward I just get Uncaught TypeError: Cannot call a class as a function when I try to use @Provider('JSONEditor', {useClass: JSONEditorProvider})

Do I have to use provide instead?

**Comment by MikeRyan52** [comment]
Yes, you need to use the provide function:

```js
provide('JSONEditor', { useClass: JSONEditorProvider })
```

**Comment by waeljammal** [comment]
Thanks
