### ISSUE TITLE
child parent communication with ng-forward

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#46]
I have a parent directive and child directive
In the child directive i need to call a function of the parent
In angular1 i simply require the controller of the parent directive and call it
How would i do it with ng-forward ?

**Comment by aciccarello** [comment]
Maybe pass the function through a property on the child component?

**Comment by MikeRyan52** [comment]
There is hidden functionality in ng-forward that let's you do this the "Angular 1" way:

```js
import {Component, Require} from 'ng-forward';

@Component({ selector: 'child' })
@Require('^parent', 'child')
class ChildCmp{
  static link($scope, $el, $attrs, requires){
    let [parent, self] = requires;
    self.parent = parent;
  }
} 
```

However, the Angular 2 way is a little murkier. You have a few options:

1. Pass the function down as @aciccarello recommends
2. Pass down an event emitter and let your child component subscribe to it
3. Create a service to handle the cross directive communication

**Comment by timkindberg** [comment]
Also you can create an output event on the child and have the parent listen for the event. I feel as though components should be 'dumb' in that they don't know about anything except themselves. 

```js
import {Component, EventEmitter} from 'ng-forward';

@Component({ 
    selector: 'child', 
    outputs: ['thingHappened']
})
class ChildCmp{
    thingHappened = new EventEmitter();
    someMethod() {
        thingHappened.next({payload: 'for parent'});
    }
}

@Component({
    selector: 'parent',
    template: '<child (thing-happened)='parent.onThingHappened($event.detail)'></child>'
})
class ChildCmp{
    onThingHappened(detailObj) {
        assert(detailObj.payload === 'for parent');
    }
}

```
