### ISSUE TITLE
@Input and @Output annotations missing

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#48]
The annotations are missing.
The workaround in the meantime are the input and output properties of the @Component annotation

**Comment by david-gang** [comment]
Hi @timkindberg ,
I still cannot import it.
Isn't there something missing in index.d.ts?
Like 
```typescript
import {Input, Output} from './cjs/decorators/input-output';
export { Module, Metastore, OpaqueToken, Provider, provide, Component, Directive, Inject, Injectable, Input, Output, Pipe, Providers, events, EventEmitter, bootstrap, bundle, getInjectableName, bundleStore, providerStore, componentStore };
```

Thanks,
David

**Comment by timkindberg** [comment]
Woops! I've added it to index's exports. Sorry about that!
