### ISSUE TITLE
passing function in component

### ISSUE THREAD

**Issue by daniele-zurico** [ngUpgraders/ng-forward#49]
Hi all,
I've created a component:

```js
$scope.onCustomEvent = function (properties, promise) {
            if (properties == 'image') {
                promise.resolve('url');
            }
        };
```
```html
<json-editor [(data)]="dataMock"  (on-custom-event)="onCustomEvent" >
```
In my component I do:
```js
@Component({
    selector: 'json-editor',
    events: [],
    inputs: ['data','onCustomEvent']
})
export default class JsonEditor {
  onCustomEvent;
  constructor() {
   new PluginInitializer(this.onCustomEvent);
  }
}
```

but this.onCustomEvent is undefined. 
What is the right way to pass it? I missed something?
thanks.

**Comment by MikeRyan52** [comment]
You need to import EventEmitter and initialize onCustomEvent to a new instance of EventEmitter:

```js
import {Component, EventEmitter} from 'ng-forward';

@Component({
  selector: 'json-editor',
  inputs: ['data'],
  outputs: ['onCustomEvent']
})
class JsonEditor{
  onCustomEvent = new EventEmitter();
}
```

**Comment by timkindberg** [comment]
If its a question that we think we've answered let's just close it and let it be reopened if needed.

**Comment by daniele-zurico** [comment]
Thanks for the fast reply. 
I've found the issue:

[code]
WRONG
< json-editor [(data)]="dataMock" (on-custom-event)="onCustomEvent" >
[/code]

[code]
CORRECT
< json-editor [(data)]="dataMock" (on-custom-event)="onCustomEvent($event)" >
[/code]

;)

thanks
