### ISSUE TITLE
How to get dependencies with jasmine for testing

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#52]
Hi all,

In angular1 we were used in jasmine to require the classes with:
```javascript
beforeEach(function() {


		module('x');
		 inject(function (_y_) {
			 y = _y_;
		 });
	});
```

In ng-forward all objects live in a big module.
How do i get to this module?

I could theoretically import the classes myself, but then i would have to make all dependency injection myself which is not so nice.

Any thoughts?

Thanks,
David

**Comment by MikeRyan52** [comment]
We have a testing library we are working on. We do not have this built yet. See #10
