### ISSUE TITLE
angular core directives with square brackets

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#53]
Hi,

ng-if in angular2 is written either *ng-if or [ng-if]
https://github.com/angular/angular/blob/d32f58926dd15a5771f5e3a3c2b77ea41c03b98b/modules/angular2/src/directives/ng_if.ts

How are the plans for ng-forward?

The same question is for ng-class.

Thanks,
David

**Comment by MikeRyan52** [comment]
We currently have no plans of back porting these directives, but wouldn't mind a PR for them either!
