### ISSUE TITLE
How to depend a service on another angular 1 module 

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#55]
Let's say i have an old angular module X which has a service A.
Now i want to write a service B which gets the service A injected.
I need essentially something like providers in the components annotation but there isn't something like this.

When i try to write 
```javascript
@Inject('X','A')
class B {
}
```

I get
>Error: [$injector:unpr] Unknown provider:AProvider

**Comment by MikeRyan52** [comment]
The Angular 2 way is to export your service and a list of providers that service depends on:

```js
@Inject('$state')
export class MyService{ }

export default [ 'ui.router' ];
```

Consuming it:
```js
import {Component} from 'ng-forward';
import myServiceProviders, {MyService} from './MyService';

@Component({
  selector: 'my-component',
  providers: [ myServiceProviders ]
})
class MyComponent{ }
```

I highly recommend going that route. If you need something more flexible that doesn't have an Angular 2 analog, you can use the undocumented `@Providers` decorator used internally by the `@Component` decorator.

**Comment by david-gang** [comment]
Hi @MikeRyan52 
Thanks for your prompt answer. 
I had actually problems with injecting any angular 1 directive.
For example if i depend on angular1 directive 'a'

and i write in components 

@Component({
directives:['a']
})

I get an error:
"Module 'a' is not available!"

Regarding the example you sent me, who created myServiceProviders?
Is it something which is created behind the scenes?

**Comment by MikeRyan52** [comment]
`myServiceProviders` is the default export of the `MyService.js` module.

Just to be clear, if you need the directive `'ui-sref'` from `'ui.router'`, you actually have to put `'ui.router'` in the `directives` array instead of `'ui-sref'`

**Comment by david-gang** [comment]
thanks for the clarification
