### ISSUE TITLE
(submit) expression is evaluated multiple times

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#56]
Hi all,

ng-submit doesnt look equivavlent to (submit).
My problem was that when i have a function (submit)="doSomething() it is called multiple times.
This also makes some sense, because if it is a simple directive then it is a part of the digest cycle and scope inheritance (My explaination).
Therefore it is still unsafe to use this.

Thanks,
David

**Comment by timkindberg** [comment]
I guess just use ng-submit for now.
