### ISSUE TITLE
$scope.$watch

### ISSUE THREAD

**Issue by daniele-zurico** [ngUpgraders/ng-forward#58]
Hello all guys,
I don't know if that problem was already solved (i've take a look on the previous bugs but there is nothing on that).

So I've created a component like that:

```javascript
<my-component [(data)]="serverData"></my-component>
```

serverData is updated from clickEvent or after n minutes and inside my component I've:

```javascript
$scope.$watch('je.data', (n) => { 
 //perform action
});
```

Obviously it's a failure point for angular 2.0. How I can avoid that?

tnx

**Comment by david-gang** [comment]
What is exactly the problem?

**Comment by MikeRyan52** [comment]
One of the features we have planned is to support opt-in lifecycle events just like Angular 2. Preferably, we'd like this to be a launch feature for ng-forward.

In your example, lifecycle events would work like this:

```js
@Component({ selector: 'my-component' })
class MyComponent{
  onChange(propertyName: string, changes: propertyChange){
    console.log(`Property: ${propertyName}, oldValue: ${changes.oldValue}, newValue: ${changes.newValue}`);
  }
}
```

Until this lands, you'll unfortunately need to continue injecting $scope and manually creating watchers.
