### ISSUE TITLE
TypeScript import results in "Cannot invoke an expression whose type lacks a call signature."

### ISSUE THREAD

**Issue by Verdilac** [ngUpgraders/ng-forward#62]
I'm trying to include `ng-forward` in my TypeScript 1.6 project, but import results in errors.

This is my .ts file:

	import {Component} from '../../../node_modules/ng-forward/cjs/index';
	@Component({
		selector: 'test',
		template: `<div onclick="test()"></div>`
	})
	class Test{
		test() {
			console.log("test")
		}
	}

This is my tsconfig.json:

	{
		"compilerOptions": {
			"target": "es5",
			"module": "commonjs",
			"sourceMap": true,
			"preserveConstEnums": true,
			"experimentalDecorators": true
		}
	}

And those are errors from gulp-typescript:

	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(2,4): error TS1131: Property or signature expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(11,3): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(11,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(13,18): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(14,14): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(15,17): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(16,15): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(17,12): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(18,13): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(19,11): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(20,16): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(21,2): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(21,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(21,23): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(23,4): error TS1131: Property or signature expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(28,3): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(28,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(30,14): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(31,17): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(32,11): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(33,16): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(34,2): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(34,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/component.d.ts(34,23): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(2,4): error TS1131: Property or signature expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(4,3): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(4,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(6,15): error TS1109: Expression expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(7,2): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(7,4): error TS1128: Declaration or statement expected.
	<project_path>/node_modules/ng-forward/cjs/decorators/directive.d.ts(7,23): error TS1109: Expression expected.

**Comment by MikeRyan52** [comment]
Yup, sorry, this one was my fault. I've published a new build: 0.0.1-alpha.7. Please note that you will still get some TS errors (it won't find the name Map or the namespace ng), but it will build correctly and you will get proper type hinting for the decorators.

Also, you should be able to change your import statement to something like:
```ts
import {Component} from 'ng-forward/cjs';
```
