### ISSUE TITLE
ngForward as a build step

### ISSUE THREAD

**Issue by ocombe** [ngUpgraders/ng-forward#63]
Hello !

I like the idea behind ngForward (writing angular 2 code for ng1 is awesome), but I think that it would be more suitable as a build step, maybe as a babel plugin.
Do you think that it's something that could be done ?

This way you would write ng2 code, compile & get ng1 code on the otherside, no need to load the ngForward library along with angular.

**Comment by timkindberg** [comment]
I was thinking of this too, but was unsure that people would like the output. I'm personally not versed in babel plugins :/

**Comment by ocombe** [comment]
Honestly once you start working with angular 2, you stop looking at the output since typescript is transpiled to ES5 and you don't want to read that.
You'd just have to make sure that the build step keeps the source maps accurate (which would be the case with a babel plugin).

I'm not versed in that too, but it looks like a good use case. I'm not sure if that's hard to write, we should summon @sebmck here and ask him :)

**Comment by ocombe** [comment]
Why did you close this ?

**Comment by pbastowski** [comment]
Sorry, finger slipped while reading on iphone :)

**Comment by ocombe** [comment]
okay :P

**Comment by pbastowski** [comment]
This is a very interesting proposition, actually, to transpile angular2 into angular1.

**Comment by ocombe** [comment]
Do you see this as a possibility ? I haven't checked out the code yet, so I don't know how it works internally.

**Comment by pbastowski** [comment]
Possibility, yes. But, I haven't given this idea enough thought yet to say any more.

**Comment by timkindberg** [comment]
Unfortunately I'm gonna close this. This idea just isn't the short term goal of this project so I know it's not where we are headed. I'm definitely not saying it's a bad idea, I just have to manage the issues and this seems closable.
