### ISSUE TITLE
two issues with alpha 7

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#66]
Hi,

I am getting the following error:
>Uncaught ReferenceError: 
>Reflect is not defined_map @ metastore.ts:7
>get @ metastore.ts:15
>(anonymous function) @ providers.ts:20
>(anonymous function) @ inject.ts:44
>(anonymous function) @ a.service.ts:2
>__decorate @ a.service.ts:2
>(anonymous function) @ a.service.ts:7
>124.ng-forward @ a.service.ts:32
>s @ _prelude.js:1
>...

It comes from the @Injectable annotation.

I cannot check the case more, because somehow chrome cannot get the source code of metastore.
Maybe something is bad with the source map?

**Comment by MikeRyan52** [comment]
Can you include the reflect-metadata polyfill before ng-forward to see if that fixes the issue? I'm realizing now that we aren't including the polyfill ourselves. I'll fix this in the next release.

As for the sourcemaps, I'll take a look. Thanks!

**Comment by david-gang** [comment]
Hi @MikeRyan52 ,
Do i need to do it for every file of the app, or will it suffice in one file?
Thanks,
David

**Comment by MikeRyan52** [comment]
It will suffice in one file.

**Comment by timkindberg** [comment]
@david-gang please let us know if that worked for you. I'm closing this, reopen if you still have issues.

**Comment by david-gang** [comment]
I will get back to you by Sunday eod

**Comment by drejohnson** [comment]
I'm getting same error once I switched to Babel 6. I have the reflect-metadata polyfill imported and my Babel presets are 'es2015' and 'stage-0'

**Comment by david-gang** [comment]
Hi @timkindberg ,
The first issue was resolved by importing the reflect-metadata library.
As there is no new release in npm:
* I forked the repo (For any case, I would also be able to perform small PRS :-) )
* Fetched the newest master
* Ran npm install
* Ran npm test
* Copied the files from the build folder
I still don't see the source code of metastore.js.
There were two new issues when looking through the chrome developer tools:-)
* The source files of the source maps were not under ng-forward, but rather in the root dir
The files were empty.

The source code of the dependencies of ng-forward were in place (despite the fact they were transpiled files instead of ts files :-( ) .

**Comment by MikeRyan52** [comment]
Hi @david-gang: I've gone ahead and published v0.0.1-alpha.8 for you. Let me know if it works!

**Comment by david-gang** [comment]
Hi
I will check it tomorrow 
Thanks a lot

**Comment by david-gang** [comment]
hi @MikeRyan52 . The problem still persists.

**Comment by david-gang** [comment]
Hi,

We have source maps.
So i will close this issue.

Thanks,
David
