### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by hannahhoward** [ngUpgraders/ng-forward#7]

**Comment by pbastowski** [comment]
Sorry for the mess above. I was just seeing if we can have more than one person assigned to a task, but it would appear that we can not. Or is there a way to do it?

**Comment by timkindberg** [comment]
I like the new readme!

Only thing I would change at the moment is the wording that ng-forward's audience is only for new codebases or for learning. I think the plan is for it to be an integral (although optional) part of upgrading, even for existing large ng1 projects.

**Comment by hannahhoward** [comment]
@timkindberg I was under the impression that ng-upgrade was the recommended strategy for that? Maybe the best way is to saw it's "ideal" target audience is people writing new codebases, cause I think that's true -- if I were starting an ng 1.x app today, I'd have a hard time seeing why I wouldn't use ng-forward, or at least another decorator library. On the other hand, if I had a giant app of oldschool 1.x code, I might just wait and upgrade to ng2 proper. Anyway, mainly I was trying to not stop on the NG team's toes with that description -- having their support is important I think even if we might think our codebase is a more core upgrade strategy than they do :)

**Comment by timkindberg** [comment]
@hannahhoward I suppose maybe someone like @petebacondarwin should let us know how it should be worded. I don't want to over or under sell it.

**Comment by timkindberg** [comment]
@petebacondarwin can you chime in on the wording pls?

**Comment by petebacondarwin** [comment]
In our talk we suggested that ng-forward could be used as part of an upgrade strategy, which could also include ng-upgrade. I think the jury is still out on the very best strategy and I expect that there isn't a one size fits all solution.

In the talk we gave equal sway to the two projects and I think there is value in developers considering both. So I agree that we should not downplay ng-forward too much; that we should point out that there are a variety of options available, of which ng-forward plays a part; that ng-forward can also be used even whether or not upgrade is your aim, as it can make you ng1 code and development cleaner.

**Comment by timkindberg** [comment]
Thanks Pete.

**Comment by timkindberg** [comment]
I finally reviewed the whole thing in depth, I made some changes based on Pete's response and a couple changes to reflect the current codebase.

**Comment by petebacondarwin** [comment]
That's one kick-ass README. We'll done everyone.
Quick mods:

* I am lead developer not project manager, for what it is worth 
* the ng-upgrade links have got the brackets the wrong way round

**Comment by timkindberg** [comment]
Fixed
