### ISSUE TITLE
Export Map and Set interface with ng-forward bundle

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#78]
When using browserify with tsify i get an error:

> node_modules/ng-forward/cjs/classes/metastore.d.ts(9,55): Error TS2304: Cannot find name 'Map'.

**Comment by timkindberg** [comment]
Try this: https://github.com/Microsoft/TypeScript/issues/3290

**Comment by david-gang** [comment]
Hi,

Thanks for the pointer.
But shouldn't this be in one of the definition files of ng-forward?
After all it is one of the ng-forward classes which causes the warning.

Thanks,
David

**Comment by joakimjm** [comment]
Alternatively use install the es6-shim typings

tsd install es6-shim

That's what ng-forward uses internally.

**Comment by timkindberg** [comment]
Yeah maybe we should include the interface in our bundle. @MikeRyan52 thoughts?
