### ISSUE TITLE
Fix controller delayed instantiation for one-way properties / non-component directives

### ISSUE THREAD

**Issue by hannahhoward** [ngUpgraders/ng-forward#8]

**Comment by petebacondarwin** [comment]
@hannahhoward can you elaborate on this?

**Comment by timkindberg** [comment]
@MikeRyan52 what is the problem here?

**Comment by MikeRyan52** [comment]
I don't recall. Closing this for now.

**Comment by timkindberg** [comment]
Does this have anything to do with this test not passing?

https://github.com/ngUpgraders/ng-forward/blob/master/src/decorators/providers/component.spec.js#L377-L395

@MikeRyan52 that test doesn't pass though I would expect it to. However, if you uncomment the console log in the test, it passes! So weird. 

Can anyone take a look at it?
