### ISSUE TITLE
in alpha 0.08 suddenly the bindings don't work

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#82]
Now in every place where i have `<mycomp [attribute-x] = "ctrl.y()">` I get 
TypeError: Cannot read property  of undefined
I cannot trace the problem because problems in the source map

This is the full stack error:

angular.js:12477 TypeError: Cannot read property 'x' of undefined
    at setBindingUsed (http://localhost:8000/a/lib/bundle.js:127126:40)
    at Y.<anonymous> (http://localhost:8000/a/lib/bundle.js:127118:17)
    at Function.assign (native)
    at exports.default (http://localhost:8000/a/lib/bundle.js:127342:12)
    at new ddo.controller (http://localhost:8000/a/lib/bundle.js:126472:57)
    at Object.invoke (http://localhost:8000/a/lib/bundle.js:56381:17)
    at extend.instance (http://localhost:8000/a/lib/bundle.js:61039:34)
    at nodeLinkFn (http://localhost:8000/a/lib/bundle.js:60151:36)
    at http://localhost:8000/a/lib/bundle.js:60422:13
    at processQueue (http://localhost:8000/a/lib/bundle.js:66648:28)(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246processQueue @ angular.js:14753(anonymous function) @ angular.js:14761Scope.$eval @ angular.js:15989Scope.$digest @ angular.js:15800Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:23554eventHandler @ angular.js:3298run @ core.js:96zoneBoundFn @ core.js:69focusElement @ angular-material.js:17037(anonymous function) @ angular-material.js:16973(anonymous function) @ angular-material.js:1156processQueue @ angular-material.js:1155(anonymous function) @ angular.js:17855completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784arguments.(anonymous function) @ functions.js:22(anonymous function) @ core.js:76run @ core.js:96zoneBoundFn @ core.js:69
angular.js:12477 TypeError: Cannot read property 'changeFunction' of undefined

This is urgent as i cannot downgrade to alpha7. There it downloads reactive/rxjs 0.10.

so basically i am stuck

**Comment by MikeRyan52** [comment]
Seems like it might be related to #81 

Did you upgrade to Babel 6 by chance?

**Comment by david-gang** [comment]
I am not using babel.
I am using browserify and tsify with typescript

**Comment by david-gang** [comment]
I get the exception at lib/util/directive-controller.ts at line 28.
> Object.assign(instance, caller);

Would it interest you to get the values of instance and caller.
Are there any additional details i can provide?

**Comment by david-gang** [comment]
the good news are that it works with alpha7 and a little tweak in npm-shrinkwrap to download the correct version of rx.

**Comment by timkindberg** [comment]
I don't understand. @david-gang is this a problem with our codebase or one of our dependencies?

**Comment by david-gang** [comment]
Hi @timkindberg,
It is not a problem with one of my dependencies.
Rather in alpha 7 the dependencies were not well defined.

**Comment by david-gang** [comment]
this is not connected to #81 
I built now from master after 82 was closed and experienced the same problem

**Comment by david-gang** [comment]
Now that we have source maps via #99 I see more :-)

The function fails here:

in inputs-builder.js

 function createHiddenPropSetter(BIND_TYPE, __privateKey) {
        return function (val) {
            this[__privateKey] = val;
            if (isDefined(val)) {
                setBindingUsed(BIND_TYPE, localKey);
            }
            if (controller[__using_binding][localKey] === BIND_TYPE) {
                this[localKey] = val;
            }
        };
    }
controller[__using_binding] is undefined.

Now we have just to understand why

**Comment by eXaminator** [comment]
I have the same problem.

It seems that [these lines](https://github.com/ngUpgraders/ng-forward/blob/master/lib/properties/inputs-builder.ts#L58-L62) do not create the expected object on the controller, thus it is not defined further down the line. Sadly I also don't have any idea how you could fix that right now.

**Comment by brandonroberts** [comment]
@david-gang @eXaminator I'm gonna blame it on the Symbol() in https://github.com/ngUpgraders/ng-forward/blob/master/lib/properties/inputs-builder.ts#L33-L36.

Change those to strings and see if that helps.

```js
  let __stringKey = '__stringKey';
  let __oneWayKey = '__oneWayKey';
  let __twoWayKey = '__twoWayKey';
  let __using_binding = '__using_binding';
```

**Comment by eXaminator** [comment]
I just did that myself (only form `__using_binding`) and it worked...

**Comment by timkindberg** [comment]
ugh... I really want to use Symbols... so when you inspect/debug in dev tools you don't see a million auto-generated properties/getters/setters on your class instance objects.

I may have time to look at this tonight to see if there is a way to keep the Symbols.

**Comment by timkindberg** [comment]
I'm trying to work on this right now... if anyone can hop on gitter and help me recreate the bug?

**Comment by timkindberg** [comment]
Can someone please create a plunkr that reproduces this bug? I'm not getting it.

http://plnkr.co/edit/ktxXKHyHQ5DLcixe6kpO?p=preview

**Comment by eXaminator** [comment]
I'll have a look at this tonight and see if I can create a broken plunker somehow.

**Comment by david-gang** [comment]
I did not reproduce exactly the problem but if you change 

```html
 <inner-app (event1)="app.onIncrement()" (event2)="app.onIncrement()"
                   [message1]="app.message1" [(message2)]="app.message2" message3="Hey, inner app... nothin'">
        </inner-app>
```

to

```html
 <inner-app (event1)="app.onIncrement()" (event2)="app.onIncrement()"
                   [message1]="app.getMessage1()" [(message2)]="app.message2" message3="Hey, inner app... nothin'">
        </inner-app>
```
and change message1 to a function:

```javascript
 getMessage1() {
      return "Hello World";
    }
```

then suddenly you don't see an input

**Comment by david-gang** [comment]
Hi,

I think i have the error.
We have just to add zone.js to the plunkr.

Thanks,
DAvid

**Comment by david-gang** [comment]
http://plnkr.co/edit/B1XmxWwDadT5OslB7SeX?p=preview

**Comment by eXaminator** [comment]
I can confirm this. I removed zone.js from my project and everything works.

**Comment by timkindberg** [comment]
So zone doesn't like symbols?

**Comment by david-gang** [comment]
Closing :-)
