### ISSUE TITLE
Why Input Output decorators are not exported?

### ISSUE THREAD

**Issue by eesdil** [ngUpgraders/ng-forward#83]
Having not exported the Input/Output I cannot use them. As it fails with Input is not function error.
Using jspm.

**Comment by david-gang** [comment]
it was fixed at https://github.com/ngUpgraders/ng-forward/commit/9a2608930a30122d0827e25eb6d1b35681645fc6
it will be released in the next version

**Comment by eesdil** [comment]
thank you
