### ISSUE TITLE
Cannot bind attributes (@Input) for @Directive

### ISSUE THREAD

**Issue by eesdil** [ngUpgraders/ng-forward#84]
Is it possible to add extra attributes to @Directive? As it doesnt seem to add the @Input() decorator...
It is working fine with @Component.

**Comment by timkindberg** [comment]
You'd have to access other attrs with $attrs, which you can inject into the constructor

```js
@Directive()
@Inject('$attrs')
class MyDirective {
  constructor($attrs) {
    console.log($attrs.someOtherAttr)
  }
}
```
