### ISSUE TITLE
$event object is not correct payload

### ISSUE THREAD

**Issue by daniele-zurico** [ngUpgraders/ng-forward#88]
Hi all I take a look on other issues that you have but I haven't found a reply to my question (the only one that seems very similar is #46 but seems that they use old implementation).

I've a component: 

```

Html:
(click)="tlc.selectItem(node);

Js:

@Output('onSelectedItem')
onSelectedItem = new EventEmitter();

selectItem(node) {
        this.onSelectedItem.onNext(node);
    }

```

In my parent component I do:

```
html:
(on-selected-item)="tree.onSelectedItem($event)"

Js:
onSelectedItem(evt){
        console.log(evt);
    }

```

The problem is that node is inside CustomEvent. So to access to my data I've to do something like:
```
evt.originalEvent.<myData>
```
Is something wrong? I expect that I can do 
```
evt.<myData>
```
thanks a lot

**Comment by timkindberg** [comment]
Can you do evt.detail?

**Comment by daniele-zurico** [comment]
yes inside detail there isn't nothing. Undefined

**Comment by eXaminator** [comment]
Shouldn't the `$event` object be whatever was passed to the `next()` call? As explained [here](https://angular.io/docs/ts/latest/guide/template-syntax.html#-event-and-event-handling-expressions)? I can't find anything about a `detail` key there.
