### ISSUE TITLE
@Output not working

### ISSUE THREAD

**Issue by eesdil** [ngUpgraders/ng-forward#94]
Not sure it is connected to any open issues as I didnt see similar.
The binding is working with ouputs: [''] binding but not with @Output

```js
@Component({
    selector: 'so-test',
    controllerAs: 'vm',
    outputs: ['soClick'],
    template: `
        <button type="button" (click)="vm.back()"></button>
        `
})
@Inject('$element')
class Test {
    constructor(private $element) { }

    // @Output('soClick') click = new EventEmitter();

    back() {
        this.$element.triggerHandler('soClick')
    }
}

@Component({
    selector: 'so-test-parent',
    controllerAs: 'vm',
    directives: [Test],
    template: `
        <so-test (so-click)="vm.clicked()"></so-test>
        `
})
@Inject('$element')
class TestParent {
    constructor() { }

    clicked() {
        console.log('parent');
    }
}

```
This is working, but if I change it to @Ouput it stops working.
Using the npm version of ngForward

**Comment by timkindberg** [comment]
Probably because we forgot to add @Input and @Output to the library's exports :(

We are going to publish a new release soon!

**Comment by eesdil** [comment]
But I have added to my index:
```
exports.Input = _decoratorsInputOutput.Input;
exports.Output = _decoratorsInputOutput.Output;
```
And for Input I had error message when I didnt have it there...
Also it is working fine if I add the attributes to the "outputs:[]" and using next with the property

**Comment by timkindberg** [comment]
Hmm ok. I'll take a look.

**Comment by timkindberg** [comment]
Try this instead to trigger the event
```js
back() {
    this.click.next()
}
```

Sorry for the very late response.

**Comment by timkindberg** [comment]
Is this still broken for you?

**Comment by timkindberg** [comment]
I'm gonna close this because it's working just fine for me and I don't see any special use-case here. Please reopen if you still have problems.
